### ISSUE TITLE
Handle http redirect in case of infoblox cluster

### ISSUE THREAD

**Issue by IKatsu** [theforeman/smart_proxy_dns_infoblox#31]
I'm dealing with infoblox in a cluster setup and occasionally the cluster dns entry (infoblox.blabla.com) will point at a server that is not the current master.
The result of this is that the api will return a http redirect to the master, this causes a fail with whatever is attempting to be done:
'unexpected token at '<HTML><HEAD><META HTTP-EQUIV="REFRESH" CONTENT = "0; URL=<current master ip>'

I'm not sure how feasible this is due to certificates but it would be nice if the plugin could follow the redirect.

**Comment by timdeluxe** [comment]
@IKatsu Can you explain a bit more, how exactly you've setup your cluster? Did you follow some Infoblox documentation about this? We are also using a HA setup, but never experienced your issue. I wonder that the passive node does a redirect via HTML Meta Tags, on the documentation i read about VRRP for HA and there no HTML Meta redirect is involved. I even tried to contact our passive nodes directly and they do not accept HTTP requests at all.
It might be possible to react to 302/301 redirects in the code, but reacting to HTML meta tags will be pretty complicated and usually is made for browsers only...

**Comment by TechTamer** [comment]
I think I can explain this.  It's not about HA; i.e. it's not about redirecting from passive node; it's about redirecting to grid members.  If you configure http redirect in the config, and go to grid member that is _NOT_ the current grid master, it gives a redirect to the current grid master.  This config can be found at Infoblox GUI >> Grid >> Grid Manager >> Edit >> Advanced Mode >> General >> Advanced >> Enable GUI Redirect from Member.  I had to turn it off because it would confuse people and there's a better approach.

IMHO, this is not a problem for the foreman project to solve.

If it helps, what I do is setup a cname to the gui.  I also have a cname for ibx-api because, while not used often, it's possible to offload the api to a different box.  I create a san cert with all the names I need in it.  Whenever the grid master moves, I manually update the cname(s).  I put in a feature request to infoblox 12 years ago to make this an automated record, but gave up on hoping that would happen.

**Comment by IKatsu** [comment]
I actually forgot about this report.

So the problem was that the plugin wasn't following a http redirect given by the infoblox member it tried to access and thus crapped out where instead it could maybe have followed the redirect and worked, and not the fact that infoblox was borked.
When this occurred infoblox was in some weird state due to an update that had gone less than stellar and it didn't update its own dns record to point at the active master iirc. (I don't manage our infoblox servers)

So again, this isn't about fixing a bad infoblox install, this is about error handling by this plugin in case some weird infoblox state happens to exist.
The dns record for infoblox was pointing at a grid member that was like 'hey i'm broken/currently not the master, go to this member instead'. 
That's all there is to it. Not a huge deal, doesn't happen that often as infoblox is fairly stable, but it can happen apparently.
It just takes time to convince networking people that something of theirs is broken when it appears to be working for them as the browser does follow the redirect.

**Comment by timdeluxe** [comment]
@IKatsu 
> So again, this isn't about fixing a bad infoblox install, this is about error handling by this plugin in case some weird infoblox state happens to exist.

Do i understand it right, that the error you got, is the one you mentioned in your opening post?
It will be rather complicated to extend the plugin to react to such an error, when it is such a rare condition.

Are you fine with just closing this issue, as the situation is really rare as you stated by yourself and TechTamer also mentioned that the Foreman project should not solve such an issue?

**Comment by IKatsu** [comment]
Yes that's right, it's just your basic redirect. If it's too complicated to do with the way the plugin is written then I agree it's not worth doing.  Maybe just something to keep in mind if there's ever a major rewrite for whatever reason.
I can't remember if it gave a 301 code like was suggested by the first response and the infoblox side has been fixed long ago so i can't really check either :)
I'll just close this.
